"""ClawBound Runtime Contracts — public API surface."""

from .types import (
    # Literal types
    ExecutionMode,
    TaskType,
    Complexity,
    RiskLevel,
    DomainSpecificity,
    OutputKind,
    SideEffectIntent,
    SegmentOwner,
    SegmentCandidateReason,
    TrimReason,
    RejectionReason,
    TargetArtifactKind,
    ToolRiskLevel,
    ToolCategory,
    ToolExecutionStatus,
    ToolOutputMediaType,
    StructuredOutputKind,
    SignalLossRisk,
    LoopTermination,
    # Decision trace
    DecisionStep,
    DecisionTrace,
    # Tier 1: TaskSpec
    TargetArtifact,
    TaskSpec,
    # Tier 1: RuntimePolicy
    ContextBudget,
    ToolProfilePolicy,
    ScopeBounds,
    ApprovalPolicy,
    IterationPolicy,
    RuntimePolicy,
    # Tier 1: PromptSegment
    AdmittedFull,
    AdmittedTrimmed,
    Rejected,
    SegmentAdmissionOutcome,
    PromptSegment,
    BudgetUtilization,
    PromptAssemblyStats,
    # Tier 4: PromptEnvelope
    PromptEnvelope,
    # Tier 1: Local Context & Retrieval
    LocalContextItem,
    RetrievalUnit,
    KernelAsset,
    # Tier 1: Signal types
    TestFailure,
    TestSummary,
    TestResultsSignal,
    BuildError,
    BuildWarning,
    BuildOutputSignal,
    LintExample,
    LintRule,
    LintOutputSignal,
    DirectoryEntry,
    DirectoryListingSignal,
    JsonResponseSignal,
    GenericSignal,
    StructuredSignal,
    CompressionMetrics,
    # Tier 2: Tool & Signal data
    ToolDefinition,
    ToolExecuteParams,
    ToolResult,
    SignalBundle,
    # Module interfaces
    RuntimeConfig,
    PromptBuildInput,
    # Provider-facing types
    ModelMessage,
    ModelToolCall,
    ModelRequest,
    FinalAnswer,
    ToolCalls,
    ModelError,
    ModelResponse,
    ModelAdapter,
    # Action gate
    ActionAllowed,
    ActionDenied,
    ActionGateDecision,
    # Loop types
    LoopConfig,
    LoopStepEvent,
    LoopResult,
    LoopInput,
    # Session types
    SessionTurn,
    SessionBounds,
    SessionSnapshot,
    # Orchestrator types
    ToolRegistration,
    OrchestratorDiagnostics,
    OrchestratorInput,
    OrchestratorResult,
)

__all__ = [
    "ExecutionMode",
    "TaskType",
    "Complexity",
    "RiskLevel",
    "DomainSpecificity",
    "OutputKind",
    "SideEffectIntent",
    "SegmentOwner",
    "SegmentCandidateReason",
    "TrimReason",
    "RejectionReason",
    "TargetArtifactKind",
    "ToolRiskLevel",
    "ToolCategory",
    "ToolExecutionStatus",
    "ToolOutputMediaType",
    "StructuredOutputKind",
    "SignalLossRisk",
    "LoopTermination",
    "DecisionStep",
    "DecisionTrace",
    "TargetArtifact",
    "TaskSpec",
    "ContextBudget",
    "ToolProfilePolicy",
    "ScopeBounds",
    "ApprovalPolicy",
    "IterationPolicy",
    "RuntimePolicy",
    "AdmittedFull",
    "AdmittedTrimmed",
    "Rejected",
    "SegmentAdmissionOutcome",
    "PromptSegment",
    "BudgetUtilization",
    "PromptAssemblyStats",
    "PromptEnvelope",
    "LocalContextItem",
    "RetrievalUnit",
    "KernelAsset",
    "TestFailure",
    "TestSummary",
    "TestResultsSignal",
    "BuildError",
    "BuildWarning",
    "BuildOutputSignal",
    "LintExample",
    "LintRule",
    "LintOutputSignal",
    "DirectoryEntry",
    "DirectoryListingSignal",
    "JsonResponseSignal",
    "GenericSignal",
    "StructuredSignal",
    "CompressionMetrics",
    "ToolDefinition",
    "ToolExecuteParams",
    "ToolResult",
    "SignalBundle",
    "RuntimeConfig",
    "PromptBuildInput",
    "ModelMessage",
    "ModelToolCall",
    "ModelRequest",
    "FinalAnswer",
    "ToolCalls",
    "ModelError",
    "ModelResponse",
    "ModelAdapter",
    "ActionAllowed",
    "ActionDenied",
    "ActionGateDecision",
    "LoopConfig",
    "LoopStepEvent",
    "LoopResult",
    "LoopInput",
    "SessionTurn",
    "SessionBounds",
    "SessionSnapshot",
    "ToolRegistration",
    "OrchestratorDiagnostics",
    "OrchestratorInput",
    "OrchestratorResult",
]
